-- MySQL Script generated by MySQL Workbench
-- 11/16/16 14:18:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
CREATE SCHEMA `casadocodigo` ;


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema casadocodigo
-- -----------------------------------------------------
CREATE USER 'casa' IDENTIFIED BY 'casa';

GRANT ALL ON `casadocodigo`.* TO 'casa';
GRANT SELECT ON TABLE `casadocodigo`.* TO 'casa';
GRANT SELECT, INSERT, TRIGGER ON TABLE `casadocodigo`.* TO 'casa';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `casadocodigo`.* TO 'casa';
GRANT EXECUTE ON ROUTINE `casadocodigo`.* TO 'casa';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
